name: 💡 Request Case Analysis
description: Suggest a company/product for Product-Channel Fit analysis
title: "[REQUEST] "
labels: ["case-request", "triage"]
projects: []
assignees:
  - Quintas0658
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Request a Case Study Analysis
        
        Know a company with an interesting Product-Channel Fit story? Just tell us about it and we'll do the research!
        
        **Examples:** "Can you analyze how Discord found its gaming communities?" or "I heard Notion failed on Product Hunt but succeeded elsewhere..."
        
  - type: input
    id: company-name
    attributes:
      label: 🏢 Company/Product Name
      description: Which company should we analyze?
      placeholder: e.g., Discord, Notion, Figma, Clubhouse
    validations:
      required: true
      
  - type: textarea
    id: why-interesting
    attributes:
      label: 🤔 Why is this interesting?
      description: What makes you think this company has a good Product-Channel Fit story?
      placeholder: e.g., "I heard they failed on traditional marketing but exploded on TikTok" or "They seem to have found a unique community that loves them"
    validations:
      required: true
      
  - type: textarea
    id: what-you-know
    attributes:
      label: 💭 What do you know about their story?
      description: Share any details you've heard about their growth or channel discovery (optional)
      placeholder: e.g., "I read they started in gaming Discord servers" or "Saw the founder tweet about Reddit being their main channel"
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: 🔥 How interested are you in this analysis?
      description: Help us prioritize which cases to research first
      options:
        - 🔥🔥🔥 Super interested - I really want to learn from this!
        - 🔥🔥 Pretty interested - Would be cool to see
        - 🔥 Mildly curious - Just throwing it out there
    validations:
      required: true
