name: 💡 Feature Request
description: Suggest an improvement for the PCF Cases website
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - Quintas0658
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        
        Thanks for helping improve PCF Cases! Your suggestions make the site better for everyone.
        
  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Description
      description: What problem would this feature solve?
      placeholder: Describe the issue or limitation you've encountered
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: 💭 Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your ideal solution
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: 📊 Category
      description: What type of feature is this?
      options:
        - User Interface/Design
        - Case Study Analysis
        - Navigation/Search
        - Data Visualization
        - Performance
        - SEO/Marketing
        - Other
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternative Solutions
      description: Any alternative approaches you've considered?
      placeholder: Other ways this could be implemented
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Screenshots, examples, or other relevant information
      placeholder: Any additional details that would help understand the request
    validations:
      required: false
